# This workflow enforces pull request requirements
name: pull request requirements

on: [pull_request]

jobs:
  enforce-target:
    runs-on: ubuntu-latest
    steps:
      - name: require target
        # Require that pull requests target the correct branch.
        if: github.base_ref == 'master' && github.head_ref != 'development'
        uses: actions/github-script@0.9.0
        with:
          script: |
            throw "All pull requests MUST target the 'development' branch."
